### ISSUE TITLE
Does prebid creative need to have Ad technology provider declared? 

### ISSUE THREAD

**Issue by adops-tcs** [kmjennison/dfp-prebid-setup#103]
I noticed a warning on the newly created prebid creatives _**"We found ad technology providers that you haven't declared."**_ 

I believe it's related to the new Google feature: https://support.google.com/admanager/answer/9972771?hl=en

It's also mentioned on prebid.org: https://docs.prebid.org/adops/setting-up-prebid-for-amp-in-dfp.html

<img width="937" alt="Screen Shot 2020-09-10 at 12 11 44 PM" src="https://user-images.githubusercontent.com/50155367/92760848-1354f900-f35f-11ea-8f20-253fae54afc1.png">

Does this script need to be modified to include this new feature?  Thank you!

**Comment by kmjennison** [comment]
Yes, Prebid has [instructions here](https://docs.prebid.org/adops/step-by-step.html#step-2-add-a-creative). 

At this point, I'm going to consider it out of scope of `dfp-prebid-setup` to modify that creative setting, given that there are regulatory implications for the user to consider. I recommend manually modifying the ATP settings after creatives are made or considering adding a network-wide rule, if desired. GAM docs here: https://support.google.com/admanager/answer/9835267?hl=en&ref_topic=28145

In the future, `dfp-prebid-setup` could include an easier option to modify creative and/or set the ATP settings.

**Comment by adops-tcs** [comment]
Thank you @kmjennison ! Make an update on the netowork level took care of all our existing prebid creatives.
