### ISSUE TITLE
Regarding custom targeting

### ISSUE THREAD

**Issue by soman** [kmjennison/dfp-prebid-setup#106]
I need to attach some static custom targeting for each line litem. Currently only one targeting attached. hb_pb = 1.01/1.02
Some custom targeting like m1_page_type = article, node_id = 1001 etc.

I would like to know how to achieve this?
It's urgent for me so I will be very happy if someone help about the issue.

Thanks,
Soman

**Comment by kmjennison** [comment]
Hi Soman, this isn't currently supported. Related: #84 

You can probably achieve what you're looking for by modifying source code in [get_custom_targeting.py](https://github.com/kmjennison/dfp-prebid-setup/blob/de941b2d98501d65da6beeedcdfd27b4b92aad69/dfp/get_custom_targeting.py).
