### ISSUE TITLE
GAM 360 issue

### ISSUE THREAD

**Issue by pajica** [kmjennison/dfp-prebid-setup#107]
HI 
The code works perfectly in Ad Manager (free version) but in Ad Manager 360 (Premium version) it doesn't work. 
I cannot get the list of orders
      Getting all orders...
      No additional orders found.

When I try to get the placements  (python -m dfp.get_placements) I get some lines listed and at the end, No DFP placement found... (see attached screenshot
![3-25-2021 1-29-20 PM](https://user-images.githubusercontent.com/80746001/112539549-5c562300-8d6e-11eb-968b-5b0abb7cfbcb.png)
)
What needs to be changed in code so I can make it work in a paid version of the DFP?
thanks
Pajica

**Comment by kmjennison** [comment]
Can you confirm the placement with name "Run of Site" exists?

**Comment by pajica** [comment]
Yes. The same I'm getting for advertiser which exists also in DFP.

**Comment by pajica** [comment]
![3-25-2021 1-51-43 PM](https://user-images.githubusercontent.com/80746001/112542184-7d6c4300-8d71-11eb-82cd-826df290bad5.png)
![3-25-2021 1-44-45 PM](https://user-images.githubusercontent.com/80746001/112542225-88bf6e80-8d71-11eb-8daf-4ceece2da7e8.png)

**Comment by kmjennison** [comment]
Interesting. Could you also double check that your user / service account has administrator access? You could double-check by calling the GAM API manually to list placements or orders.

I don't use GAM 360 at the moment, and the integration tests on this code run against a free GAM account, so I'm unsure if it's a problem with this library or not.

**Comment by pajica** [comment]
When I call orders with python -m dfp.get_orders
this is what I get
![image](https://user-images.githubusercontent.com/80746001/112544959-e1dcd180-8d74-11eb-9983-a806c6da8b60.png)

**Comment by pajica** [comment]
and there are at least a 100 orders

**Comment by kmjennison** [comment]
In that case, it seems possible the user doesn't have access or it's hitting the wrong GAM account.

**Comment by pajica** [comment]
I have created the same user on all premium and free accounts. On all free accounts it works like a charm but on premium the same issue everywhere. I tried a couple of accounts.

**Comment by pajica** [comment]
Is there any script that I can check if the connection is working?

**Comment by kmjennison** [comment]
You could try the [googleads Python library](https://github.com/googleads/googleads-python-lib) directly.

**Comment by pajica** [comment]
Just to let you know that it is working on premium Ad Manager 360 as well. The connection was the problem. 
When I created a service account, I forgot to select All Teams. When I did it, the program start working.

thank you so much.
