### ISSUE TITLE
API Version Deprecated

### ISSUE THREAD

**Issue by al2six** [kmjennison/dfp-prebid-setup#109]
Hello, I just tried to use this for the first time and when I went to validate that is was working by getting orders, I got the following error: `Error summary: {'faultMessage': "[ApiVersionError.UPDATE_TO_NEWER_VERSION @ version; trigger:'Version v202008 was deprecated and is now disabled. Please check the DoubleClick for Publishers blog for more information or contact us via the support forum.']"`

I'm on Python 3.9.4

**Comment by kmjennison** [comment]
Thanks, updated!
