### ISSUE TITLE
DFP API Sunset -v201702

### ISSUE THREAD

**Issue by madhurdamle** [kmjennison/dfp-prebid-setup#37]
Just received a mail from DFP that the API version on which this is based is going to be deprecated on 30th March 2018. Do we have any plans to upgrade the API version that this tool is currently based on?

**Comment by kmjennison** [comment]
Thanks for bringing this up. I'll try to update this if I have some spare time, but I welcome anybody else doing so. I don't [see any breaking changes](https://developers.google.com/doubleclick-publishers/docs/rel_notes#v201711), but we should create a test order against a live DFP account to be sure (in addition to making sure the existing tests pass).

**Comment by kmjennison** [comment]
Fixed in #48. Note that you'll have to use the newer JSON key type for the service account..
