### ISSUE TITLE
Cannot create order due to duplicate archived name

### ISSUE THREAD

**Issue by ahmedeltawil** [kmjennison/dfp-prebid-setup#54]
After I ran this tool, I realized one of the configurations I've set was incorrect so I archived the created the orders in DFP, adjusted the config, and then started the process again. Unfortunately, there seems to be an issue in re-creating the same orders using the same names I've used previously, even though it was archived. Anyone seen this issue before and know how to get around it?

**Comment by kmjennison** [comment]
Order names in DFP (now Google Ad Manager) need to be unique, even from archived orders. I just confirmed this in the GAM console by cloning an order, archiving the original order, and trying rename the cloned order to the original name, and it wouldn't let me.

I recommend adding a date (or some other modifier) to the new order's name.
