### ISSUE TITLE
How to set up for people who are not developers?

### ISSUE THREAD

**Issue by mwaqarakram94** [kmjennison/dfp-prebid-setup#60]
Hey, 

I am trying to set up this on my windows PC , However I am having a lot of difficulties. 

Can you please tell which softwares are required to run this program and how to run, 

Please just a few steps to set me in right direction.

Best Regards

**Comment by kmjennison** [comment]
Hi! You'll want to:
* [Install Python](https://www.python.org/downloads/release/python-371/). You might want to look for "getting started" guides for Windows.
* [Set up Git](https://help.github.com/articles/set-up-git/), which will let you clone this repository to your computer (in other words, copy the code). Alternatively, you can just download the repository as a zip file from the top-right of the [main page](https://github.com/kmjennison/dfp-prebid-setup).
* Where the instructions say to run commands, you'll want to run them in Window's "Command Prompt" in the same directory where you copied this repository.

Hope this helps to get you started.

**Comment by mwaqarakram94** [comment]
Thank you so much 👍

**Comment by mwaqarakram94** [comment]
I am stuck on this part, where do I run this? 
Clone this repository.
Run pip install -r requirements.txt.

**Comment by mwaqarakram94** [comment]
Done with installs now, doing python -m dfp.get_orders  

However command prompt is not recognizing python command

**Comment by mwaqarakram94** [comment]
So done with creating my first order , Thank you so much, how do I modify it to send only top bids configuration, only thing which changes is I don't want to pass hb_bidder key value

**Comment by mwaqarakram94** [comment]
Thank you so much kevin, I appreciate all your help.
