### ISSUE TITLE
Support video line items

### ISSUE THREAD

**Issue by mwaqarakram94** [kmjennison/dfp-prebid-setup#61]
Hey can we use this tool for video line items as well, 

For Prebid for video

http://prebid.org/adops/setting-up-prebid-video-in-dfp.html

**Comment by kmjennison** [comment]
With some modifications to the creative (see [code here](https://github.com/kmjennison/dfp-prebid-setup/blob/master/dfp/create_creatives.py#L52)), you should be able to. I haven't tried it myself, but it looks like you'd use the VAST redirect creative type: https://developers.google.com/ad-manager/api/reference/v201802/CreativeService.VastRedirectCreative

**Comment by schoenbl** [comment]
@mwaqarakram94 were you ever able to configure this?

I have my creative config set to:
`  config = {
    'name': name,
    'advertiserId': advertiser_id,
    'vastRedirectType': 'LINEAR',
    'vastXmlUrl': 'https://prebid.adnxs.com/pbc/v1/cache?uuid=%%PATTERN:hb_uuid%%',
  }`

And I'm receiving an error of: KeyError: 'vastRedirectType'

**Comment by kmjennison** [comment]
@andrew-sotiriou Thanks! Implementing #84 should make the tool flexible enough to support this.
