### ISSUE TITLE
Currently the tool creates 400 creatives  and one creative per line item

### ISSUE THREAD

**Issue by mwaqarakram94** [kmjennison/dfp-prebid-setup#62]
I have reviewed the #13  and #14 

However upon checking tool is currently creating only one creative per line item.

and 400 creatives per order. 

Prebid recommend having only 5 to 6 creatives per order and assoicating all 6 creatives to each line item.

Please can you add that support ? 

Best Regards

**Comment by kmjennison** [comment]
How many placements do you have in the `DFP_TARGETED_PLACEMENT_NAMES` setting? The default is to add the a number of creatives equal to the number of placements you're targeting.

You should also be able to override this with the `DFP_NUM_CREATIVES_PER_LINE_ITEM` setting.
