### ISSUE TITLE
ImportError: cannot import name ad_manager

### ISSUE THREAD

**Issue by ericsson66** [kmjennison/dfp-prebid-setup#70]
Hi!

I downloaded the last version of the line item generator, but can't manage to make it work. I'm certainly missing something...

-- 
iMac-de-Eric:dfp2 xxx$ python -m dfp.get_orders
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/xxx/Prog/dfp2/dfp/get_orders.py", line 6, in <module>
    from googleads import ad_manager
**ImportError: cannot import name ad_manager**

-- 

Any idea?

Best,
Eric

**Comment by kmjennison** [comment]
@ericsson66 Can you confirm you've installed the [dependencies](https://github.com/kmjennison/dfp-prebid-setup/blob/master/requirements.txt)? What version of `googleads` do you have installed?

**Comment by ericsson66** [comment]
@kmjennison thanks for your prompt reply

While instaling the dependencies, I had this message:
googleads 15.0.1 has requirement PyYAML<4.0,>=3.11, but you'll have pyyaml 4.2b4 which is incompatible.

So I edited the requirement.txt to switch pyyaml to 3.11
Then I managed to have googleads 15.0.1 installed.

**Comment by ericsson66** [comment]
Update, I'm working on another computer right now and it's working smoothly until I get an error from a Python related error (using macOS). 

Maybe it's better to close the issue for now as I feel it depends on my system.

**Comment by ericsson66** [comment]
Ok it works now... was due to:
1. Obsolete os X environment (lol)
2. Python environment needed tweakings on macOs Mojave

**Comment by schoenbl** [comment]
I'm getting this exact same error. I previously used the same repository to build line items, and now it no longer works. The only thing that has changed is that i upgraded to mojave. @ericsson66 what tweaks did you make to your python environment?
