### ISSUE TITLE
Switch to Prebid's "universal creative"

### ISSUE THREAD

**Issue by kmjennison** [kmjennison/dfp-prebid-setup#73]
See: http://prebid.org/overview/prebid-universal-creative.html

**Comment by abiandreb** [comment]
I was just going to ask about that here but you have already answered my question. 
I'm an adops and I'm using this tool very often. I'm not strong in python but is there a possibility of technical problems with the ad serving when using the code of the creative, which was before? 
Some times we can see extremely low fill rate with some bidders despite the fact that we were receiving around 80% fillrate with direct codes from those bidders.

**Comment by kmjennison** [comment]
@abiandreb The original Prebid creative still works fine as far as I know, but you could check Prebid's issues if you think there might be a problem. I likely won't be able to help diagnose a problem with an integration, ad server, or Prebid itself.
