### ISSUE TITLE
Getting error ModuleNotFoundError: No module named 'googleads'

### ISSUE THREAD

**Issue by soman** [kmjennison/dfp-prebid-setup#92]
python -m dfp.get_orders
aceback (most recent call last):
File "C:\Program Files\Python38\lib\runpy.py", l
  return _run_code(code, main_globals, None,
File "C:\Program Files\Python38\lib\runpy.py", l
  exec(code, run_globals)
File "C:\laragon\www\dfp-prebid-setup\dfp\get_or
  from googleads import ad_manager
duleNotFoundError: No module named 'googleads'

I am using Windows 10
Python version: 3.8.1 (64 bit)

**Comment by soman** [comment]
Issue solved.

**Comment by proper-luke** [comment]
@soman how did you solve this?
